// Generated by CoffeeScript 1.6.1
(function() {
  var initTabs;

  initTabs = function() {
    $('.slide1').flexslider({
      slideshow: false,
      animation: "slide"
    });
    $('.slide2').flexslider({
      slideshow: false,
      animation: "slide"
    });
    return $('.slide3').flexslider({
      slideshow: false,
      animation: "slide"
    });
  };

  initTabs();

  jQuery(function() {
    var timer;
    timer = null;
    $("#back-top").on("click", function(e) {
      e.preventDefault();
      return $("body, html").animate({
        scrollTop: 0
      }, 800);
    });
    $('.sub-menu').hide();
    $('.infotip').hide();
    $('.order-btns button').click(function(e) {
      e.preventDefault();
      $('.order-btns button').removeClass('active');
      $(this).addClass('active');
      if ($(this).hasClass('block')) {
        return $('.listing').removeClass('list').addClass('block');
      } else if ($(this).hasClass('list')) {
        return $('.listing').removeClass('block').addClass('list');
      }
    });
    $('#social li, #social-footer li').hover(function() {
      return $('span.tooltip', this).fadeIn('fast');
    }, function() {
      return $('span.tooltip', this).fadeOut('fast');
    });
    $('select').customSelect();
    $('.category-menu > li a').on("click", function(e) {
      if ($(this).attr('href') === "#") {
        e.preventDefault();
      }
      $(".menu.active").fadeOut();
      return $(this).next().addClass("active").fadeIn(200);
    });
    $("body").on("click", function() {
      return $('.sub-menu.active').fadeOut(200);
    });
    $('.category-menu > li').click(function(e) {
      return e.stopPropagation();
    });
    return $(".top-widget").find("h2").find("a").hover(function() {
      var _this = this;
      return timer = setTimeout(function() {
        return $(_this).next().fadeIn(200);
      }, 500);
    }, function() {
      clearTimeout(timer);
      timer = null;
      return $(this).next().fadeOut(200);
    });
  });

  $('#tabs').tabs();

  $('.tabs a').on("click", function() {
    return initTabs();
  });

  $(window).resize(function() {
    return $('select').css("width", "100%").trigger('update');
  });

}).call(this);
